### ISSUE TITLE
Add support to named SQL Instances

### ISSUE THREAD

**Issue by gh057k33p3r** [JuniorDark/RustyHearts-API#11]
Hi!

I tried to set up the API, and ran into a problem because I had a named SQL Instance.

I added this to both **dbConfig** and **authDBConfig** and it ended up working. It would be nice to have a **DB_INSTANCE** option in the .env

<pre>
  options: {
    encrypt: process.env.DB_ENCRYPT === 'true',
    instanceName: 'SQLExpress'
  },
</pre>

The instanceName should be conditionally appended to the options object if the DB_INSTANCE config key has a value.

Thanks in advance!

**Comment by JuniorDark** [comment]
Hello, DB_SERVER env variable handle named instances, format is: SERVERNAME\INSTANCENAME

example: DB_SERVER=DESKTOP-LP5QOID\RUSTYHEARTS

Ensure the SQL Server Browser service is running. This service is essential for resolving named instances.

**Comment by gh057k33p3r** [comment]
Thanks! I had a failed mssql installation at first, no idea why
